### ISSUE TITLE
Create ImHungry App

### ISSUE THREAD

**Issue by amaclean2** [amaclean2/imhungry#1]
## ImHungry App
You give it a bunch of food you like or eat regularly, when you eat it and it tells you a reminder of something you might like to eat.  
With enough data from different users, it can tell you what other people like to eat by feeding the data to an AI model.

### Todo List
- [x] Create a default app
- [x] #2
- [x] Add items to the list
- [x] Save the list to device storage
- [x] Have a button that asks the app what should I eat
- [ ] #3
- [ ] Send a notification for a recommendation at a scheduled time
